audit_header: false
title: '-- MARKET -- Real Estate Video Blog with Ryan Ahearn'
description: >-
  Our mission at -- CLIENT BRAND -- is to be your best resource for -- MARKET --
  real estate advice. Whether you are a buyer, seller, or investor, our team of
  professionals can answer any questions you might have about real estate. If
  you are looking to buy or sell a home, you can get all the information and the
  latest updates, tips, and tricks from The -- CLIENT BRAND --, your
  professional -- MARKET -- Real Estate Agents.
show_custom_links: false
custom_links:
  - title:
    url:
client:
  name: Ryan Ahearn
  title:
  license_number: 'CalDRE #01878842'
  about_markdown: >-
    I feel that having the right real estate agent means having an agent who is
    committed to helping you buy or sell your home with the highest level of
    expertise in your local market. This means also to help you in understanding
    each step of the buying or selling process. This commitment level has helped
    me build a remarkable track record of delivering results.


    Whether you are an experienced investor or a first time buyer, I can help
    you in finding the property of your dreams. Feel free to browse through my
    profile and please don't hesitate to reach out for any of your real estate
    needs!
  market:
  brand: Ryan Ahearn Team
  brokerage: Keller Williams
  address: '6265 Greenwich Dr. Ste 251 San Diego, CA 92122'
  phone: 619-540-2634
  phone_type:
  phone2:
  phone2_type:
  email: ryan@ryanahearnteam.com
  url: 'http://everyhomesandiego.com'
CTAs:
  first_CTA_text: Home Valuation
  first_CTA_URL: 'https://www.everyhomesandiego.com/what-is-my-home-worth'
  second_CTA_text: Home Search
  second_CTA_URL: 'https://www.everyhomesandiego.com/'
sidebar_CTA:
  - CTA_image_path: /img/cta-images/004.jpg
    CTA_title: What’s Your -- MARKET -- Home Worth?
    CTA_text: >-
      Are you thinking of selling your home or interested in learning about home
      prices in your neighborhood? We can help you.
    CTA_link_text: Free Home Value Report
    CTA_url: 'https://www.everyhomesandiego.com/what-is-my-home-worth'
second_sidebar_CTA:
  - CTA_image_path2: /img/cta-images/005.jpg
    CTA_title2: Looking for a -- MARKET -- Home?
    CTA_text2: Search the entire MLS for your -- MARKET -- home.
    CTA_link_text2: Search the MLS
    CTA_url2: 'https://www.everyhomesandiego.com/'
lender:
  show_section: false
  header_text: Preferred Lender
  headshot_path: 'http://fillmurray.com/200/200'
  logo_path: /img/logo.png
  logo_path_2:
  name: Bill Murray
  brand: Lender Co.
  phone: 555-555-5555
  email: bill@murray.com
  url: 'http://eyegoop.com'
socials:
  review_sm_icons: false
  facebook_url:
  linkedin_url: 'https://www.linkedin.com/in/ryan-ahearn-596a906/'
  gplus_url:
  youtube_url: 'https://www.youtube.com/channel/UCRP3SuSXfnzRU16ESditz3g'
  twitter_url: 'https://twitter.com/RyanAhearnTeam'
  instagram_url:
  pinterest_url:
  zillow_url: 'https://www.zillow.com/profile/Ryan-Ahearn/'
  trulia_url:
  yelp_url:
  podcast_url:
podcast:
  title: '-- MARKET -- Real Estate Podcast with -- CLIENT NAME --'
  categories:
    - Education
  image: /img/podcast.jpg
  subtitle: >-
    Learn all the tips, tricks and more for buyers and sellers in the -- MARKET
    -- Area Real Estate Market
  description: >-
    If you are looking to buy or sell a home, get all the information and the
    latest updates, tips, and tricks from -- CLIENT BRAND -- - your professional
    -- MARKET -- Real Estate Agents.
  keywords: >-
    Real Estate for sale, Real Estate agents, top real estate agents, local real
    estate agents, find a real estate agent, houses for sale in -- MARKET --,
    home selling tips, home for sale, home buying, home buying process, property
    finder, property search, property, real estate market, estate agent,
    realestate, real estate listings, buying a house, homes for sale, mls, home
    buyer
  author: '-- CLIENT NAME --'
images:
  client_headshot_path: /img/headshot.jpg
  hero_logo_path: /img/logo.png
  logo_width_number: 25
  hero_text:
  hero_background_hex: '#999999'
  hero_image_path: /img/background.jpg
  post_cover: /img/cover.jpg
site_colors:
  brand_color: '#2970b8'
  theme_color: '#000000'
  theme_text_color: '#5d9bd3'
  main_body_color: '#ffffff'
  main_body_text_color: '#353535'
navbar_colors:
  border_bottom:
header_shadow:
  h_shadow: 0px
  w_shadow: 2px
  shadow_spread: 7px
  shadow_color: 'rgba(0, 0, 0, 0)'
buttons:
  button_radius_number: 0
  button_padding_width_number: 10
  button_padding_height_number: 15
  button_border_color: '#ffffff'
  button_background_color: 'rgba(0, 0, 0, 0)'
  button_text_color: '#123456'
  secondary_button_border_color: '#ffffff'
  secondary_button_background_color: 'rgba(0, 0, 0, 0)'
  secondary_button_text_color: '#ffffff'